version: '3.4'

services:
  password-manager:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"

  mongo:
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db