apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-manager
  namespace: ar-world
  labels:
    app: password-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-manager
  template:
    metadata:
      labels:
        app: password-manager
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "password-manager"
        dapr.io/app-port: "80"
        dapr.io/config: "ar.config"
    spec:
      containers:
        - name: password-manager
          image: "ghcr.io/kannan-ar/password-manager:latest"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /probes/ready
              port: 80
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 12
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /probes/healthz
              port: 80
            failureThreshold: 6
            periodSeconds: 10
