apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - name: my-web
        image: kannanar.azurecr.io/ar-web-front:1.0
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: aracr
---
apiVersion: v1
kind: Service
metadata:
  name: my-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: my-web