name: password-manager

on:
  push:
    branches:
      - develop
      - master
    paths:
      - 'src/password-manager/api/**'

  workflow_dispatch:

jobs:
  set-env:
    name: Set Environment Variables
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.main.outputs.version }}
      image: ${{ steps.main.outputs.image }}
      repository: ${{ steps.main.outputs.repository }}
    steps:
      - id: main
        run: |
          echo "version=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
          echo "image=password-manager" >> $GITHUB_OUTPUT
          echo "repository=ghcr.io/kannan-ar/ar-packages" >> $GITHUB_OUTPUT

  package-service:
    name: Package Service
    runs-on: ubuntu-latest
    needs: set-env
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/password-manager/api/Dockerfile
          push: true
          tags: |
            ${{ needs.set-env.outputs.repository }}/${{ needs.set-env.outputs.image }}:latest
            ${{ needs.set-env.outputs.repository }}/${{ needs.set-env.outputs.image }}:${{ needs.set-env.outputs.version }}
      - name: Update deployment yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'manifests/base/deployments/password-manager.yaml'
          propertyPath: 'spec.template.spec.containers.0.image'
          value: ${{ needs.set-env.outputs.repository }}/${{ needs.set-env.outputs.image }}:${{ needs.set-env.outputs.version }}
          commitChange: 'false'
          branch: 'master'
          message: 'Updated password manager deployment manifest.'
          createPR: 'false'
          updateFile: 'true'
      - name: Echo yaml
        run: |
          cat manifests/branch/base/deployments/password-manager.yaml
      - name: Promote deployment
        uses: dmnemec/copy_file_to_another_repo_action@main
        env: 
          API_TOKEN_GITHUB: ${{ secrets.CR_PAT }}
        with:
          source_file: manifests/base/deployments/password-manager.yaml
          destination_repo: kannan-ar/Code-Samples
          destination_folder: manifests/base/deployments
          git_server: github.com
          user_email: kannanpala@gmail.com
          user_name: kannan-ar