name: promote-manifests

on:
  push:
    branches:
      - 'master'
    paths:
      - 'manifests/**'

  workflow_dispatch:

jobs:
  echo-success:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "It worked!"